docker_box/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as static_serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dockit.urls', namespace='docker_box')),    
]

urlpatterns += [
    url(r'^static/(?P<path>.*)$', static_serve, {'document_root': settings.STATIC_ROOT}),
]

dockit/urls.py
from django.conf.urls import url
from .views import index, logout_user
from .views import host_stats
from .views import docker_images, search_images, pull_image, pull_image_progress, launch_image, remove_image
from .views import container_list, container_details, start_container, restart_container, stop_container, edit_container, delete_container, container_stats
from .views import users_list, new_user, edit_user, delete_user, change_password, container_diff, terminal
from .views import ip_list, new_ip, edit_ip, delete_ip, backup_container, ssh_access, container_top, container_info

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^logout/$', logout_user, name='logout'),

    url(r'^host_stats/$', host_stats, name='host_stats'),

    url(r'^images/$', docker_images, name='docker-images-list'),
    url(r'^images/search$', search_images, name='search-images'),
    url(r'^images/pull/(?P<uuid_token>[-\w]+)/$', pull_image, name='pull-image'),
    url(r'^images/pull-progress/(?P<uuid_token>[-\w]+)/$', pull_image_progress, name='pull-image-progress'),
    url(r'^images/(?P<name>.+)/launch/$', launch_image, name='launch-image'),
    url(r'^images/(?P<name>.+)/remove/$', remove_image, name='remove_image'),

    url(r'^container/list/$', container_list, name='container-list'),
    url(r'^container/(?P<container_id>[-\w]+)/$', container_details, name='container-details'),
    url(r'^container/(?P<container_id>[-\w]+)/start/$', start_container, name='start-container'),
    url(r'^container/(?P<container_id>[-\w]+)/restart/$', restart_container, name='restart-container'),
    url(r'^container/(?P<container_id>[-\w]+)/stop/$', stop_container, name='stop-container'),
    url(r'^container/(?P<container_id>[-\w]+)/edit/$', edit_container, name='edit_container'),
    url(r'^container/(?P<container_id>[-\w]+)/delete/$', delete_container, name='delete_container'),
    url(r'^container/(?P<container_id>[-\w]+)/stats/$', container_stats, name='container_stats'),
    url(r'^container/(?P<container_id>[-\w]+)/backup/$', backup_container, name='backup_container'),
    url(r'^container/(?P<container_id>[-\w]+)/change-password/$', change_password, name='change_password'),
    url(r'^container/(?P<container_id>[-\w]+)/ssh-access/$', ssh_access, name='ssh_access'),
    url(r'^container/(?P<container_id>[-\w]+)/top/$', container_top, name='top'),
    url(r'^container/(?P<container_id>[-\w]+)/(?P<total>[-\w]+)/diff/$', container_diff, name='diff'),
    url(r'^container/(?P<container_id>[-\w]+)/terminal/$', terminal, name='terminal'),
    url(r'^container/info/(?P<container_id>[-\w]+)/$', container_info, name='container_info'),

    # users
    url(r'^settings/users/$', users_list, name='users-list'),
    url(r'^settings/users/new/$', new_user, name='new-user'),
    url(r'^settings/users/(?P<pk>\d+)/edit/$', edit_user, name='edit-user'),
    url(r'^settings/users/(?P<pk>\d+)/delete/$', delete_user, name='delete-user'),
    # ip address
    url(r'^settings/ip/list/$', ip_list, name='ip-list'),
    url(r'^settings/ip/new/$', new_ip, name='new-ip'),
    url(r'^settings/ip/(?P<pk>\d+)/edit/$', edit_ip, name='edit-ip'),
    url(r'^settings/ip/(?P<pk>\d+)/delete/$', delete_ip, name='delete-ip'),
]

dockit/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from dockit.utils import ImageMixin, ContainerMixin
from django.core.exceptions import ObjectDoesNotExist


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100, verbose_name="Name")
    username = models.CharField(max_length=100, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    ssh_pub_key = models.TextField(null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_short_name(self):
        """Return the email."""
        return self.email


class IP(models.Model):
    ip_addr = models.GenericIPAddressField(unique=True)
    mac_addr = models.CharField(max_length=200, null=True, blank=True)
    is_routed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.ip_addr


class Host(models.Model):
    hostname = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    ssh_port = models.CharField(max_length=10, default='22')
    docker_api_port = models.CharField(max_length=10)
    docker_network = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.ip.ip_addr


class ImageManager(models.Manager):
    def get_image(self, name, user):
        try:
            image = Image.objects.get(name=name)
            if user == image.user or user.is_superuser:
                return image
            else:
                return None
        except ObjectDoesNotExist:
            return None

class Image(models.Model, ImageMixin):
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    snapshot = models.ForeignKey('dockit.Container', models.SET_NULL, blank=True, null=True, related_name='backup')
    is_snapshot = models.BooleanField(default=False)
    objects = ImageManager()

    def __str__(self):
        return self.name


class ContainerManager(models.Manager):
    def get_container(self, container_id, user):
        try:
            container = Container.objects.get(container_id=container_id)
            if user == container.user or user.is_superuser:
                return container
            else:
                return None
        except ObjectDoesNotExist:
            return None


class Container(models.Model, ContainerMixin):
    hostname = models.CharField(max_length=100)
    container_id = models.CharField(max_length=200)
    image = models.ForeignKey(Image)
    ip = models.ForeignKey(IP)
    user = models.ManyToManyField(User)
    objects = ContainerManager()

    def __str__(self):
        return self.container_id

templates/container_info.html
{% extends "site_base.html" %}
{% load staticfiles %}
{% block title %} Container Details{% endblock %}
{% block bodycontent %}
<div class="row marl main_container">
    <div class="container">
        <h3 class="heading">Container Details</h3>
        <div class="row marl chart_row">
            <div class="col-md-6 chart_col">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div id="chart_div" style="width: 100%; height: 100%;">
                            ID: <a href="{% url 'docker_box:container-details' container.container_id %}">{{ container.container_id }}</a>
                            <br/>
                            Host Name: {{ container.hostname }}
                            <br/>
                            IP Address: {{ container.ip.ip_addr }}
                            <br/>
                            Password: {{ passphrase }}
                            <br/>
                            Created: {{ container.created }}
                            <br/>
                        </div>
                    </div>
                    <div class="panel-content">
                        <div id="curve_chart1" style="width:90%"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/docker_images.html
{% extends "base.html" %}
{% load sizes %}

{% block content %}
    <div class="row marl search_row">
        <div class="input-group">
            <input id="txt-image-search" type="text" class="form-control text-filter" name="textFilter" tabindex="1"
                   placeholder="Search docker images">
            <div class="input-group-btn">
                <button type="button" class="btn btn-primary search btn-icon" data-action="search">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>
        </div>
        <div class="search_result row">
        </div>
    </div>

    <div class="col-md-12">
        <div class="container">
            <div class="row">
                <h2 class="text-center">Images</h2>
                <div class="row">
                    {% for image in images %}
                        <div class="col-md-4 head_box">
                            <div class="box">
                                {% with image.RepoTags.0|split:":" as tags %}
                                    <div class="box-content">
                                        <h4 class="tag-title">
                                            {{ tags.0 }}
                                        </h4>
                                        <hr/>
                                        <p><i class="fa fa-tags" title="Tags"></i> {{ tags.1 }} </p>
                                        <p><i class="fa fa-image"
                                              title="Image"></i> {{ image.Id|cut:"sha256:"|slice:"12" }}</p>
                                        <p><i class="fa fa-hdd-o" title="Size"></i> {{ image.Size|filesizeformat }}</p>
                                        <p class="pull-left"><i class="fa fa-calendar"
                                                                title="Created On"></i> {{ image.Created|epoch_to_datetime }}
                                        </p>
                    <span class="launch_button">
                      <a href="{% url 'docker_box:launch-image' image.Id|cut:'sha256:'|slice:'12' %}"
                         class="btn btn-primary pull-right"> Launch</a>
                    </span>
                                    </div>
                                {% endwith %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block extra_js %}

    <script type="text/javascript">
        $('#txt-image-search').keyup(function () {
            var term = $('#txt-image-search').val();
            $(".loader").fadeIn("slow");
            $.post("{% url 'docker_box:search-images' %}", {'term': term}, function (data) {
                // console.log(data);
                if (data) {
                    $('.search_result').text('')
                    $(".loader").fadeOut("slow");
                    for (var key in data) {
                        $('.search_result').append(
                                '<div class="col-lg-12 col-md-12"><div class="card" style="background:white; padding: 10px 20px; border: 1px solid #dadada; border-radius: 5px;"><div class="card-block row"><div class="col-md-12"><h4 class="card-title">' + data[key].name + '</h4></div><div class="col-md-12"><div class="col-lg-8 col-md-8 col-sm-12"><p class="card-text">Description: ' + data[key].description + '</p></div><div class="col-lg-2 col-md-2 col-sm-6"><i class="fa fa-star"></i> ' + data[key].star_count + '</div><div class="col-lg-2 col-md-2 col-sm-6"><button class="btn btn-primary pull">Pull</button></div></div></div></div></div>'
                        );
                    }
                    $(".loader").hide();
                }
                else {
                    $('.search_result').text('')
                }
            });

        });

        /*PULL IMAGE*/
        $("body").on("click", ".pull", function (e) {
            e.preventDefault();
            imageName = $($(this).closest('.card-block').children()[0]).text()
            $('.search_result').text('')
            $(".loader").fadeIn("slow");
            $('.loadingtext').text('Downloading Image...').css({'padding-top': '10%'})
            $.post(
                    "{% url 'docker_box:pull-image' %}", {
                        imageName: imageName
                    },
                    function (data, status, xhr) {
                        console.log(data)
                        if (status == 'success') {
                            if (data['status'] == 'ok') {
                                $(".loader").fadeOut("slow");
                                window.location = '/images/'
                            }
                            else {
                                $('.loadingtext').text('Success')
                                console.log(data)
                                $(".loader").fadeOut("slow");
                                $('.search_result').text('')
                            }
                        }
                        else {
                            console.log(status)
                        }
                    });

        });
        /*END PULL IMAGE*/
    </script>

{% endblock %}

templates/ip_address.html
{% extends "site_base.html" %}
{% load paginate %}
{% load staticfiles %}
{% load sizes %}
{% block title %} Dockerbox IPs {% endblock %}
{% block bodycontent %}
    <!-- main_container starts here -->
    <div class="row marl main_container">
        <div class="container">
            <h3 class="heading">Create IP Address</h3>
            <div class="table_row">
                <form action="" name="ip_create" method="POST">
                    {% csrf_token %}
                    <table class="table table-striped table-condensed ip-list">
                        <tbody class='tb_class'>
                        <tr class='tr_class'>
                            <td>
                                <select class="ip_class form-control" name="is_routed">
                                    <option value="0">Individual IP</option>
                                    <option value="1">External Subnet IP</option>
                                </select>
                            </td>

                            <td class='ipa_class'>
                                <input class="form-control" maxlength="39" name="ip_addr" type="text" value=""
                                       placeholder="Enter IP"/>
                            </td>
                            <td class='mac_class'>
                                <input class="form-control" maxlength="39" name="mac_addr" type="text" value=""
                                       placeholder="Enter MAC"/>
                            </td>
                            <td>
                                Is Active ?
                                <input checked="checked" id="id_is_active" name="is_active" type="checkbox"/>

                            </td>
                            <td>
                                Is Available ?
                                <input checked="checked" id="id_is_available" name="is_available" type="checkbox"/>

                            </td>
                            <td>
                                <button type="submit" class="btn btn-info">Create</button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
                <h3 class="heading">Available IP addresses</h3>
                <table class="table table-striped table-condensed ip-list">
                    <thead>
                    <tr>
                        <th width="20%">IP Address</th>
                        <th width="15%">Attached to</th>
                        <th width="15%">Is Active ?</th>
                        <th width="15%">Is Available ?</th>
                        <th width="20%">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if per_page %}
                        {% paginate per_page ip_list %}
                    {% else %}
                        {% paginate 5 ip_list %}
                    {% endif %}
                    {% for ip in ip_list %}
                        <tr>
                            <td>
                                {% csrf_token %}
                                <input class="form-control" maxlength="39" name="ip_addr" type="text"
                                       value="{{ ip.ip_addr }}" disabled>
                            </td>
                            <td>
                                <a href="#">container name</a>
                            </td>
                            <td>
                                <input {% if ip.is_active %}checked="checked"{% endif %} id="id_is_active"
                                       name="is_active" type="checkbox" disabled>
                            </td>
                            <td>
                                <input {% if ip.is_available %}checked="checked"{% endif %} id="id_is_active"
                                       name="is_available" type="checkbox" disabled>
                            </td>
                            <td class="actions">
                                <a href="{% url 'docker_box:edit-ip' ip.id %}" class="edit" title="save"
                                   style="display:none;"><i class="fa fa-floppy-o"></i></a>
                                <a href="{% url 'docker_box:edit-ip' ip.id %}" class="edit" title="edit"><i
                                        class="fa fa-edit"></i></a>
                                <a href="{% url 'docker_box:delete-ip' ip.id %}" class="trash" title="delete"><i
                                        class="fa fa-trash"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% ifequal ip_list|length 0 %}
                    <div class="marl row text-center">
                        <h4>No IPs Found</h4>
                    </div>
                {% endifequal %}
                <div class="marl row text-center">
                    {% show_pages %}
                </div>
            </div>
        </div>
    </div>
    <!-- main_container ends here -->
{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            mac_html = $('.mac_class').get(0).outerHTML;
            $('.ip_class').on('change', function(){
                if(this.value == '1'){
                    $('.mac_class').remove();
                }
                else{
                    $('.ipa_class').after(mac_html);
                }
            });

            $("form[name=ip_create]").submit(function (e) {
                e.preventDefault();
                $form = $(this)
                $.post("{% url 'docker_box:new-ip' %}", $(this).serialize(), function (response) {
                    $(".error").remove();
                    if (response.error) {
                        $.each(response.errors, function (field_name, error) {
                            error = "<span class=\"error\">" + error + "</span>"
                            $form.find("[name=" + field_name + "]").after(error)
                        })
                    }
                    else {
                        window.location = ""
                    }
                });
            });

            $("a[title=edit]").click(function (e) {
                e.preventDefault();
                $row = $(this).closest("tr")
                $row.find("input[type=text]").attr("style", "")
                $row.find("input").prop("disabled", false)
                $(this).hide();
                $row.find("a[title=save]").show();
            });
            $("a[title=save]").click(function (e) {
                e.preventDefault();
                $this = $(this)
                $row = $(this).closest("tr")
                url = $(this).attr("href")
                data = $row.find("input").serialize()
                $.post(url, data, function (response) {
                    $(".error").remove();
                    if (response.error) {
                        $.each(response.errors, function (field_name, error) {
                            error = "<p class=\"error\">" + error + "</p>"
                            $row.find("[name=" + field_name + "]").after(error)
                        })
                    }
                    else {
                        $row.find("input[type=text]").attr("style", "box-shadow:none;border:none;")
                        $row.find("input").prop("disabled", true)
                        $this.hide();
                        $row.find("a[title=edit]").show();
                    }
                });
            })
        })
    </script>
{% endblock %}

templates/new_user.html
{% extends "site_base.html" %}
{% load paginate %}
{% load sizes %}
{% block title %} Dockerbox Containers {% endblock %}
{% block bodycontent %}
    <div class="row marl main_container">
        <div class="container">
            <div class="form_container ">
                <div class="col-xs-offset-3 col-xs-6 col-xs-offset-3">
                    <h3 class="heading"></h3>
                    <div class="panel panel-default form_panel">
                        <div class="panel-content">
                            <form action="" name="user_create" method="POST">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">{{ field.label }}</label>
                                        {{ field }}
                                    </div>
                                {% endfor %}
                                <div class="form-group" style="display: flex;">
                                    <button type="submit" class="btn btn-info">{% if form.email.value %}
                                        Update{% else %} Create {% endif %}</button>
                                    &nbsp;&nbsp;&nbsp;
                                    <button type="button" class="btn btn-info cancel">Cancel</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("form[name=user_create]").submit(function (e) {
                e.preventDefault();
                $form = $(this)
                $.post("", $(this).serialize(), function (response) {
                    $(".error").remove();
                    if (response.error) {
                        $.each(response.errors, function (field_name, error) {
                            error = "<span class=\"error\">" + error + "</span>"
                            $form.find("[name=" + field_name + "]").after(error)
                        })
                    }
                    else {
                        window.location = "{% url 'docker_box:users-list' %}"
                    }
                });
            });
            $(".cancel").click(function () {
                window.location = "{% url 'docker_box:users-list' %}"
            })
        })
    </script>
{% endblock %}

templates/no_access.html
<!DOCTYPE html>
<html>
<head>
	<title>no access</title>
</head>
<body>
You doesn't seems to have access to the requested resource. Contact Administrator.
</body>
</html>

templates/site_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!--<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700,800,900" rel="stylesheet">-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!--<script type="text/javascript" src="https://cdn.plot.ly/plotly-latest.min.js"></script>-->
    <!-- Custom styling plus plugins -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>
<body class="inner_pages_bg">
<!-- header starts here -->
<header>
    <nav class="navbar navbar-default">
        <div>
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'docker_box:index' %}">DockerBox</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% if user.is_superuser %}
                    <li><a href="{% url 'docker_box:docker-images-list' %}"> Images </a></li>
                    {% endif %}
                    <li><a href="{% url 'docker_box:container-list' %}">Containers</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'docker_box:users-list' %}"><i class="fa fa-users sub_icon"
                                                                       aria-hidden="true"></i>Users</a></li>
                    <li><a href="{% url 'docker_box:ip-list' %}"><i class="fa fa-cogs sub_icon" aria-hidden="true"></i>Settings</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Welcome! {% if request.user.first_name %}{{ request.user.first_name }}
                            {% else %}{{ request.user.username }} {% endif %}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'docker_box:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</header>

{% block bodycontent %}
{% endblock %}
<div class="loader">
    <div class="text-center loadingtext"></div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<script type="text/javascript">
    $(window).load(function () {
        $(".loader").fadeOut("slow");
    })
</script>
{% block extra_js %}
{% endblock %}
</body>
</html>

templates/users.html
{% extends "site_base.html" %}
{% load paginate %}
{% load staticfiles %}
{% load sizes %}
{% block title %} Dockerbox Users {% endblock %}
{% block bodycontent %}
    <!-- main_container starts here -->
    <div class="row marl main_container">
        <div class="container">
            <h3 class="heading">Users</h3>
            <div class="table_row">
                <table class="table table-striped table-condensed">
                    <thead>
                    <tr>
                        <th width="10%">Name</th>
                        <th width="20%">Email</th>
                        <th width="10%">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if per_page %}
                        {% paginate per_page users_list %}
                    {% else %}
                        {% paginate 5 users_list %}
                    {% endif %}
                    {% for user in users_list %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td class="actions">
                                <a href="{% url 'docker_box:edit-user' user.id %}" class="edit"><i
                                        class="fa fa-edit"></i></a>
                                <a href="{% url 'docker_box:delete-user' user.id %}" class="trash"><i
                                        class="fa fa-trash"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% ifequal users_list|length 0 %}
                    <div class="marl row text-center">
                    <h4>No users Found</h4>
                {% endifequal %}
                </div>
                <div class="marl row text-center">
                    {% show_pages %}
                </div>

                <br/>
            <form action="{% url 'docker_box:new-user' %}">
                <button class='btn btn_color'>Add User</button>
            </form>
            </div>
                                              
        </div>
    </div>
    <!-- main_container ends here -->
{% endblock %}